stages:
  - docker
  - test
  - release

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_TAG
      when: never
    - when: always

##########
# Docker #
##########
android-build docker-image:
  image: docker:19
  stage: docker
  services:
    - docker:19.03.0-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE/node-yarn:latest docker/node-yarn/ --build-arg SSH_DEPLOY_PRIVATE_KEY="$SSH_DEPLOY_PRIVATE_KEY"
    - docker push $CI_REGISTRY_IMAGE/node-yarn:latest
  when: manual
  allow_failure: true
  retry:
    max: 2
    when: runner_system_failure

#########
# Tests #
#########
tests:
  stage: test
  image: $CI_REGISTRY_IMAGE/node-yarn:latest
  script:
    - yarn install
    - yarn lint
    - yarn test:coverage --ci 
  when: always

#########
# Tests #
#########
generate version:
  stage: release
  image: $CI_REGISTRY_IMAGE/node-yarn:latest
  before_script:
    # Add the git trigger username and email
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
  script:
    - yarn install
    - yarn build
    - npx semantic-release
  when: on_success
  only:
    - master