name: Release

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Install semantic-release extra plugins
      run: yarn add @semantic-release/changelog @semantic-release/git --dev
    - name: Lint
      run: yarn lint-fix
    - name: Test
      run: yarn test:unit --if-present
    - name: Build
      run: yarn build      
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release